### ISSUE TITLE
Allow selecting from "abstract" classes.

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu-document-manager#22]
It MUST be possible to select from abstract (or super mapped in Doctrine terminology) classes.

This is of crucial importance when we need to select all documents which are instances of `BasePageDocument` (i.e. Home and Page documents).

```
mapping:
    base_page:
        class: BasePageDocument
        super: true
    page:
        # ...
        extends: base_page
```

``` php
$qb->from()->document('base_page');
$pages = $qb->getQuery()->execute();
```

The `extends` keyword is not required, as the same information could be inferred from class inheitance. But using it may be a short-term and performant solution.
