### ISSUE TITLE
Add "required" property to metadata mapping

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu-document-manager#24]
Allow a "required" mapping for mapped fields, e.g.

```
mapping:
     class: stdClass
     alias: foo
     phpcr_type: bar
     fields:
          foo:
              required: true
              property: foo
```
